#!/bin/bash

AMI=ami-0b152cfd354c4c7a4 # ubuntu 18.04
SECURITY_GROUP=${SECURITY_GROUP}
INSTANCE_TYPE=t2.micro
KEY_NAME=hwchen01
INSTANCE_TAG=hw-rkv-lab-si
ROOT_DISK_VOLUME=8
NUM_OF_INSTANCE=2
KEY_FILE=${KEY_FILE}
