#!/bin/bash

AMI=ami-0b152cfd354c4c7a4 # ubuntu 18.04
SECURITY_GROUP=${SECURITY_GROUP}
INSTANCE_TYPE=t2.micro
KEY_NAME=${KEY_NAME}
INSTANCE_TAG=${RKV_VM_NAME}
ROOT_DISK_VOLUME=16
NUM_OF_INSTANCE=1
KEY_FILE=${KEY_FILE}
